"""initial schema

Revision ID: a6181d2e6a96
Revises: 
Create Date: 2026-04-09 16:16:35.570440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6181d2e6a96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compradores',
    sa.Column('id_comprador', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id_comprador')
    )
    op.create_table('productores',
    sa.Column('id_productor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id_productor')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('repartidores',
    sa.Column('id_repartidor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id_repartidor')
    )
    op.create_table('entradas',
    sa.Column('id_entrada', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_productor', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('precio_compra', sa.Float(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_productor'], ['productores.id_productor'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_entrada')
    )
    op.create_table('entregas',
    sa.Column('id_entrega', sa.Integer(), nullable=False),
    sa.Column('id_comprador', sa.Integer(), nullable=False),
    sa.Column('id_repartidor', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('entregado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_comprador'], ['compradores.id_comprador'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_repartidor'], ['repartidores.id_repartidor'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_entrega')
    )
    op.create_table('detalle_entrega',
    sa.Column('id_detalle_entrega', sa.Integer(), nullable=False),
    sa.Column('id_entrega', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_entrega'], ['entregas.id_entrega'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle_entrega')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_entrega')
    op.drop_table('entregas')
    op.drop_table('entradas')
    op.drop_table('repartidores')
    op.drop_table('productos')
    op.drop_table('productores')
    op.drop_table('compradores')
    # ### end Alembic commands ###
