"""new column activo to manage soft delete

Revision ID: fc70ae167bac
Revises: 
Create Date: 2026-04-08 18:34:51.011816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc70ae167bac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detalle_entrega', type_='foreignkey')
    op.drop_constraint(None, 'detalle_entrega', type_='foreignkey')
    op.create_foreign_key(None, 'detalle_entrega', 'entregas', ['id_entrega'], ['id_entrega'], ondelete='CASCADE')
    op.create_foreign_key(None, 'detalle_entrega', 'productos', ['id_producto'], ['id_producto'], ondelete='CASCADE')
    op.drop_constraint(None, 'entradas', type_='foreignkey')
    op.drop_constraint(None, 'entradas', type_='foreignkey')
    op.create_foreign_key(None, 'entradas', 'productos', ['id_producto'], ['id_producto'], ondelete='CASCADE')
    op.create_foreign_key(None, 'entradas', 'productores', ['id_productor'], ['id_productor'], ondelete='CASCADE')
    op.drop_constraint(None, 'entregas', type_='foreignkey')
    op.drop_constraint(None, 'entregas', type_='foreignkey')
    op.create_foreign_key(None, 'entregas', 'repartidores', ['id_repartidor'], ['id_repartidor'], ondelete='SET NULL')
    op.create_foreign_key(None, 'entregas', 'compradores', ['id_comprador'], ['id_comprador'], ondelete='CASCADE')
    op.add_column('productores', sa.Column('activo', sa.Boolean(), nullable=False))
    op.add_column('productos', sa.Column('activo', sa.Boolean(), nullable=False))
    op.add_column('repartidores', sa.Column('activo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repartidores', 'activo')
    op.drop_column('productos', 'activo')
    op.drop_column('productores', 'activo')
    op.drop_constraint(None, 'entregas', type_='foreignkey')
    op.drop_constraint(None, 'entregas', type_='foreignkey')
    op.create_foreign_key(None, 'entregas', 'compradores', ['id_comprador'], ['id_comprador'])
    op.create_foreign_key(None, 'entregas', 'repartidores', ['id_repartidor'], ['id_repartidor'])
    op.drop_constraint(None, 'entradas', type_='foreignkey')
    op.drop_constraint(None, 'entradas', type_='foreignkey')
    op.create_foreign_key(None, 'entradas', 'productores', ['id_productor'], ['id_productor'])
    op.create_foreign_key(None, 'entradas', 'productos', ['id_producto'], ['id_producto'])
    op.drop_constraint(None, 'detalle_entrega', type_='foreignkey')
    op.drop_constraint(None, 'detalle_entrega', type_='foreignkey')
    op.create_foreign_key(None, 'detalle_entrega', 'productos', ['id_producto'], ['id_producto'])
    op.create_foreign_key(None, 'detalle_entrega', 'entregas', ['id_entrega'], ['id_entrega'])
    # ### end Alembic commands ###
